[package]
name = "mem"
version = "0.1.0"
compiler = "0.11.0"
entrypoint = "src/lib.typ"
repository = "https://github.com/TimeTravelPenguin/mem"
authors = ["TimeTravelPenguin <TimeTravelPenguin@gmail.com>"]
license = "MIT"
description = "A Typst package for creating compact and tested cheat sheets/memory aids for exams."
keywords = ["template", "styling", "exam", "memory", "cheatsheet"]
categories = ["fun", "components"]
